# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(300, 478)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 447))
        MainWindow.setMaximumSize(QtCore.QSize(999, 9999))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    color: #F6F6F6;\n"
"    background-color: #6B6B6B;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #F6F6F6;\n"
"    background-color: #7C7C7C;\n"
"    border: 1px solid #535EDF;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    color: #F6F6F6;\n"
"    background-color: #7C7C7C;\n"
"    border: 1px solid #2C65A2;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: black;\n"
"    background-color: #4487CF;\n"
"    border: 1px solid #2C65A2;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: black;\n"
"    background-color: #4C9CF2;\n"
"    border: 1px solid #2C65A2;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    color: #F6F6F6;\n"
"    background-color: #7C7C7C;\n"
"    border: 1px solid #2C65A2;\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.te_userEnter = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_userEnter.setGeometry(QtCore.QRect(10, 390, 231, 51))
        self.te_userEnter.setCursorWidth(1)
        self.te_userEnter.setObjectName("te_userEnter")
        self.btn_commit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_commit.setGeometry(QtCore.QRect(250, 390, 41, 51))
        self.btn_commit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons8-paper-plane-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_commit.setIcon(icon)
        self.btn_commit.setObjectName("btn_commit")
        self.te_gptAnswer = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_gptAnswer.setGeometry(QtCore.QRect(10, 10, 280, 370))
        self.te_gptAnswer.setAcceptDrops(False)
        self.te_gptAnswer.setReadOnly(True)
        self.te_gptAnswer.setOverwriteMode(True)
        self.te_gptAnswer.setCursorWidth(0)
        self.te_gptAnswer.setObjectName("te_gptAnswer")
        self.pb_progress = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.pb_progress.setGeometry(QtCore.QRect(10, 450, 281, 21))
        self.pb_progress.setMaximum(2)
        self.pb_progress.setProperty("value", 0)
        self.pb_progress.setTextVisible(False)
        self.pb_progress.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pb_progress.setInvertedAppearance(False)
        self.pb_progress.setObjectName("pb_progress")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.te_userEnter.setPlaceholderText(_translate("MainWindow", "Введите вопрос..."))
        self.te_gptAnswer.setPlaceholderText(_translate("MainWindow", "Здесь будет овтет"))
