# Form implementation generated from reading ui file 'LoginTest.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 520)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_username.setGeometry(QtCore.QRect(70, 160, 251, 41))
        self.le_username.setObjectName("le_username")
        self.le_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_password.setGeometry(QtCore.QRect(70, 210, 251, 41))
        self.le_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_password.setObjectName("le_password")
        self.btn_commit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_commit.setGeometry(QtCore.QRect(70, 260, 251, 51))
        self.btn_commit.setObjectName("btn_commit")
        self.le_password.raise_()
        self.le_username.raise_()
        self.btn_commit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_username.setPlaceholderText(_translate("MainWindow", "Имя пользователя"))
        self.le_password.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.btn_commit.setText(_translate("MainWindow", "войти"))
