# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(25, 25, 25);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTextBrowser{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(130, 130, 130);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}QMainWindow {\n"
"    background-color: rgb(25, 25, 25);\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(130, 130, 130);\n"
"    color: rgb(130, 130, 130);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_username.setGeometry(QtCore.QRect(70, 170, 250, 40))
        self.le_username.setObjectName("le_username")
        self.le_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_password.setGeometry(QtCore.QRect(70, 220, 250, 40))
        self.le_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_password.setObjectName("le_password")
        self.btn_commitLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_commitLogin.setGeometry(QtCore.QRect(70, 270, 250, 40))
        self.btn_commitLogin.setObjectName("btn_commitLogin")
        self.te_question = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_question.setGeometry(QtCore.QRect(440, 420, 271, 51))
        self.te_question.setObjectName("te_question")
        self.btn_commitQue = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_commitQue.setGeometry(QtCore.QRect(720, 420, 41, 51))
        self.btn_commitQue.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons8-paper-plane-26.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_commitQue.setIcon(icon)
        self.btn_commitQue.setIconSize(QtCore.QSize(16, 16))
        self.btn_commitQue.setObjectName("btn_commitQue")
        self.tb_answer = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tb_answer.setGeometry(QtCore.QRect(440, 30, 321, 381))
        self.tb_answer.setObjectName("tb_answer")
        self.btn_commitLogin.raise_()
        self.le_password.raise_()
        self.te_question.raise_()
        self.btn_commitQue.raise_()
        self.tb_answer.raise_()
        self.le_username.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_username.setPlaceholderText(_translate("MainWindow", "Имя пользователя"))
        self.le_password.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.btn_commitLogin.setText(_translate("MainWindow", "войти"))
        self.te_question.setPlaceholderText(_translate("MainWindow", "Введите вопрос"))
        self.tb_answer.setPlaceholderText(_translate("MainWindow", "Здесь будет ответ..."))
