# Form implementation generated from reading ui file 'regUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 390)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(25, 25, 25);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(130, 130, 130);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_key = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_key.setGeometry(QtCore.QRect(60, 160, 250, 40))
        self.le_key.setObjectName("le_key")
        self.btn_reg = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_reg.setGeometry(QtCore.QRect(60, 210, 250, 40))
        self.btn_reg.setObjectName("btn_reg")
        self.le_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_password.setGeometry(QtCore.QRect(60, 110, 250, 40))
        self.le_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_password.setObjectName("le_password")
        self.le_username_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_username_2.setGeometry(QtCore.QRect(60, 60, 250, 40))
        self.le_username_2.setObjectName("le_username_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(69, 310, 241, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_key.setPlaceholderText(_translate("MainWindow", "API-ключ"))
        self.btn_reg.setText(_translate("MainWindow", "войти"))
        self.le_password.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.le_username_2.setPlaceholderText(_translate("MainWindow", "Имя пользователя"))
        self.label.setText(_translate("MainWindow", "как получить API-ключ"))
